import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
	darkMode: 'class',
	content: ['./src/**/*.{html,js,svelte,ts}'],
	theme: {
		extend: {
			colors: {
				'surface-bright': '#393939',
				'outline-variant': '#564338',
				error: '#ffb4ab',
				'on-surface-variant': '#ddc1b3',
				'surface-dim': '#131313',
				'surface-container-lowest': '#0e0e0e',
				'tertiary-fixed': '#d4e4f6',
				'surface-container': '#201f1f',
				primary: '#ffb68d',
				background: '#131313',
				'secondary-fixed-dim': '#ffb77d',
				'primary-container': '#df7328',
				'on-primary-fixed': '#321200',
				tertiary: '#b8c8da',
				'primary-fixed-dim': '#ffb68d',
				'on-primary': '#532200',
				'on-tertiary-fixed': '#0d1d2a',
				'on-primary-fixed-variant': '#763400',
				'on-background': '#e5e2e1',
				'on-error': '#690005',
				'inverse-surface': '#e5e2e1',
				'surface-container-low': '#1c1b1b',
				'secondary-fixed': '#ffdcc3',
				secondary: '#ffb77d',
				'inverse-primary': '#9a4600',
				'on-error-container': '#ffdad6',
				surface: '#131313',
				'on-secondary-fixed': '#2f1500',
				'surface-variant': '#353534',
				'on-tertiary': '#223240',
				'surface-tint': '#ffb68d',
				'on-secondary': '#4d2600',
				'inverse-on-surface': '#313030',
				'on-surface': '#e5e2e1',
				'secondary-container': '#fd8b00',
				'tertiary-container': '#8292a3',
				'error-container': '#93000a',
				'tertiary-fixed-dim': '#b8c8da',
				'surface-container-high': '#2a2a2a',
				'on-secondary-fixed-variant': '#6e3900',
				'surface-container-highest': '#353534',
				'on-tertiary-fixed-variant': '#394857',
				'on-secondary-container': '#603100',
				'on-primary-container': '#481d00',
				'on-tertiary-container': '#1c2b39',
				'primary-fixed': '#ffdbc9',
				outline: '#a58c7f',
			},
			borderRadius: {
				DEFAULT: '0.125rem',
				lg: '0.25rem',
				xl: '0.5rem',
				full: '0.75rem',
			},
			spacing: {
				unit: '8px',
				margin: '32px',
				gutter: '24px',
				'container-max': '1280px',
			},
			fontFamily: {
				'label-sm': ['Inter', 'sans-serif'],
				h3: ['Newsreader', 'serif'],
				h1: ['Newsreader', 'serif'],
				'body-md': ['Inter', 'sans-serif'],
				h2: ['Newsreader', 'serif'],
				'body-lg': ['Inter', 'sans-serif'],
				serif: ['Newsreader', 'serif'],
			},
			fontSize: {
				'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
				h3: ['24px', { lineHeight: '1.4', fontWeight: '500' }],
				h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
				'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
				h2: ['36px', { lineHeight: '1.3', fontWeight: '600' }],
				'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
			},
			maxWidth: {
				'container-max': '1280px',
			},
		},
	},
	plugins: [forms],
}
